import type { TableSpec } from '@/src/modules/sync/domain/syncTypes'

export const SYNC_TABLE_SPECS: TableSpec[] = [
  {
    name: 'fuel_stations',
    pk: 'id',
    hasStationId: false,
    direction: 'both',
    columns: [
      'id',
      'code',
      'name',
      'address',
      'city',
      'country',
      'phone',
      'email',
      'is_active',
      'deleted_at',
      'created_at',
      'updated_at',
    ],
  },
  {
    name: 'users',
    pk: 'id',
    hasStationId: true,
    direction: 'both',
    columns: [
      'id',
      'station_id',
      'username',
      'email',
      'password_hash',
      'role',
      'full_name',
      'is_active',
      'last_login_at',
      'deleted_at',
      'created_at',
      'updated_at',
    ],
  },
  {
    name: 'customers',
    pk: 'id',
    hasStationId: true,
    direction: 'both',
    columns: [
      'id',
      'station_id',
      'buyer_name',
      'buyer_type',
      'pin',
      'passport_number',
      'business_name',
      'tin',
      'tax_ninbrn',
      'contact_phone',
      'contact_mobile',
      'contact_fax',
      'contact_email',
      'contact_website',
      'contact_person',
      'address_street',
      'address_city',
      'address_state',
      'address_province',
      'address_postal_code',
      'address_country_code',
      'country',
      'is_anonymous',
      'deleted_at',
      'created_at',
      'updated_at',
    ],
  },
  {
    name: 'transactions',
    pk: 'id',
    hasStationId: true,
    direction: 'both',
    columns: [
      'id',
      'station_id',
      'customer_id',
      'pump_number',
      'transaction_date_time',
      'total_amount',
      'volume',
      'fuel_type',
      'pos_reference',
      'status',
      'allocated_at',
      'allocated_by',
      'fiscalization_reference',
      'fiscal_document_id',
      'fiscalization_response',
      'fiscalized_at',
      'auto_fiscalized',
      'retry_count',
      'last_error',
      'deleted_at',
      'created_at',
      'updated_at',
    ],
  },
  {
    name: 'receipts',
    pk: 'id',
    hasStationId: true,
    direction: 'both',
    columns: [
      'id',
      'transaction_id',
      'station_id',
      'receipt_number',
      'html_content',
      'plain_text_content',
      'fiscal_data',
      'branding_snapshot',
      'generated_at',
      'created_at',
      'updated_at',
    ],
  },
  {
    name: 'station_settings',
    pk: 'id',
    hasStationId: true,
    direction: 'both',
    columns: [
      'id',
      'station_id',
      'linking_window_seconds',
      'unallocated_handling',
      'fiscalization_engine',
      'auto_fiscalize_enabled',
      'sync_enabled',
      'sync_time',
      'sync_timezone',
      'created_at',
      'updated_at',
    ],
  },
  {
    name: 'fiscalization_events',
    pk: 'id',
    hasStationId: true,
    direction: 'both',
    columns: [
      'id',
      'station_id',
      'transaction_id',
      'engine',
      'status',
      'reference',
      'request_payload',
      'response_payload',
      'error_message',
      'occurred_at',
      'created_at',
      'updated_at',
    ],
  },
]
