-- Replace local ATG history with one latest normalized snapshot per tank.
-- Cloud services own long-term ATG history retention.

CREATE TABLE IF NOT EXISTS tank_atg_snapshots (
  tank_id UUID PRIMARY KEY REFERENCES tanks(id) ON DELETE CASCADE,
  station_id UUID NOT NULL REFERENCES fuel_stations(id) ON DELETE CASCADE,
  product_id UUID REFERENCES products(id) ON DELETE SET NULL,
  tg_id VARCHAR(2) NOT NULL,
  doms_tank_id VARCHAR(2),
  captured_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  controller_updated_at TIMESTAMPTZ,

  product_name TEXT,
  tank_name TEXT,
  capacity_litres NUMERIC(14, 3),
  temperature_c NUMERIC(10, 3),
  tc_volume_litres NUMERIC(14, 3),
  volume_litres NUMERIC(14, 3),

  product_level NUMERIC(14, 3),
  water_level NUMERIC(14, 3),
  total_observed_volume_litres NUMERIC(14, 3),
  water_volume_litres NUMERIC(14, 3),
  gross_observed_volume_litres NUMERIC(14, 3),
  gross_standard_volume_litres NUMERIC(14, 3),
  available_room_litres NUMERIC(14, 3),
  max_safe_fill_capacity_litres NUMERIC(14, 3),
  shell_capacity_litres NUMERIC(14, 3),
  product_mass NUMERIC(16, 4),
  product_density NUMERIC(16, 6),
  product_tc_density NUMERIC(16, 6),
  density_probe_temperature_c NUMERIC(10, 3),
  sludge_level NUMERIC(14, 3),
  oil_separator_oil_thickness NUMERIC(14, 3),
  oil_separator_oil_volume NUMERIC(14, 3),
  temp_sensor_1_c NUMERIC(10, 3),
  temp_sensor_2_c NUMERIC(10, 3),
  temp_sensor_3_c NUMERIC(10, 3),
  pressure NUMERIC(16, 4),
  adjusted_volume_litres NUMERIC(14, 3),
  adjusted_tc_volume_litres NUMERIC(14, 3),
  delivered_volume_litres NUMERIC(14, 3),
  delivered_tc_volume_litres NUMERIC(14, 3),
  delivered_mass NUMERIC(16, 4),
  delivered_quantity NUMERIC(16, 4),
  tg_product_code TEXT,
  tank_group_id TEXT,
  tank_gauge_type TEXT,
  tank_inflow_control_mode TEXT,
  source_payload_hash VARCHAR(64),

  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Preserve the newest local reading when upgrading from the history-worker build.
INSERT INTO tank_atg_snapshots (
  tank_id,
  station_id,
  product_id,
  tg_id,
  doms_tank_id,
  captured_at,
  controller_updated_at,
  product_name,
  tank_name,
  capacity_litres,
  temperature_c,
  tc_volume_litres,
  volume_litres,
  product_level,
  water_level,
  total_observed_volume_litres,
  water_volume_litres,
  gross_observed_volume_litres,
  gross_standard_volume_litres,
  available_room_litres,
  max_safe_fill_capacity_litres,
  shell_capacity_litres,
  product_mass,
  product_density,
  product_tc_density,
  density_probe_temperature_c,
  sludge_level,
  oil_separator_oil_thickness,
  oil_separator_oil_volume,
  temp_sensor_1_c,
  temp_sensor_2_c,
  temp_sensor_3_c,
  pressure,
  adjusted_volume_litres,
  adjusted_tc_volume_litres,
  delivered_volume_litres,
  delivered_tc_volume_litres,
  delivered_mass,
  delivered_quantity,
  tg_product_code,
  tank_group_id,
  tank_gauge_type,
  tank_inflow_control_mode,
  source_payload_hash,
  updated_at
)
SELECT DISTINCT ON (tank_id)
  tank_id,
  station_id,
  product_id,
  tg_id,
  doms_tank_id,
  recorded_at,
  controller_updated_at,
  product_name,
  tank_name,
  capacity_litres,
  temperature_c,
  tc_volume_litres,
  volume_litres,
  product_level,
  water_level,
  total_observed_volume_litres,
  water_volume_litres,
  gross_observed_volume_litres,
  gross_standard_volume_litres,
  available_room_litres,
  max_safe_fill_capacity_litres,
  shell_capacity_litres,
  product_mass,
  product_density,
  product_tc_density,
  density_probe_temperature_c,
  sludge_level,
  oil_separator_oil_thickness,
  oil_separator_oil_volume,
  temp_sensor_1_c,
  temp_sensor_2_c,
  temp_sensor_3_c,
  pressure,
  adjusted_volume_litres,
  adjusted_tc_volume_litres,
  delivered_volume_litres,
  delivered_tc_volume_litres,
  delivered_mass,
  delivered_quantity,
  tg_product_code,
  tank_group_id,
  tank_gauge_type,
  tank_inflow_control_mode,
  source_payload_hash,
  CURRENT_TIMESTAMP
FROM tank_atg_readings
ORDER BY tank_id, recorded_at DESC, id DESC
ON CONFLICT (tank_id) DO UPDATE SET
  station_id = EXCLUDED.station_id,
  product_id = EXCLUDED.product_id,
  tg_id = EXCLUDED.tg_id,
  doms_tank_id = EXCLUDED.doms_tank_id,
  captured_at = EXCLUDED.captured_at,
  controller_updated_at = EXCLUDED.controller_updated_at,
  product_name = EXCLUDED.product_name,
  tank_name = EXCLUDED.tank_name,
  capacity_litres = EXCLUDED.capacity_litres,
  temperature_c = EXCLUDED.temperature_c,
  tc_volume_litres = EXCLUDED.tc_volume_litres,
  volume_litres = EXCLUDED.volume_litres,
  product_level = EXCLUDED.product_level,
  water_level = EXCLUDED.water_level,
  total_observed_volume_litres = EXCLUDED.total_observed_volume_litres,
  water_volume_litres = EXCLUDED.water_volume_litres,
  gross_observed_volume_litres = EXCLUDED.gross_observed_volume_litres,
  gross_standard_volume_litres = EXCLUDED.gross_standard_volume_litres,
  available_room_litres = EXCLUDED.available_room_litres,
  max_safe_fill_capacity_litres = EXCLUDED.max_safe_fill_capacity_litres,
  shell_capacity_litres = EXCLUDED.shell_capacity_litres,
  product_mass = EXCLUDED.product_mass,
  product_density = EXCLUDED.product_density,
  product_tc_density = EXCLUDED.product_tc_density,
  density_probe_temperature_c = EXCLUDED.density_probe_temperature_c,
  sludge_level = EXCLUDED.sludge_level,
  oil_separator_oil_thickness = EXCLUDED.oil_separator_oil_thickness,
  oil_separator_oil_volume = EXCLUDED.oil_separator_oil_volume,
  temp_sensor_1_c = EXCLUDED.temp_sensor_1_c,
  temp_sensor_2_c = EXCLUDED.temp_sensor_2_c,
  temp_sensor_3_c = EXCLUDED.temp_sensor_3_c,
  pressure = EXCLUDED.pressure,
  adjusted_volume_litres = EXCLUDED.adjusted_volume_litres,
  adjusted_tc_volume_litres = EXCLUDED.adjusted_tc_volume_litres,
  delivered_volume_litres = EXCLUDED.delivered_volume_litres,
  delivered_tc_volume_litres = EXCLUDED.delivered_tc_volume_litres,
  delivered_mass = EXCLUDED.delivered_mass,
  delivered_quantity = EXCLUDED.delivered_quantity,
  tg_product_code = EXCLUDED.tg_product_code,
  tank_group_id = EXCLUDED.tank_group_id,
  tank_gauge_type = EXCLUDED.tank_gauge_type,
  tank_inflow_control_mode = EXCLUDED.tank_inflow_control_mode,
  source_payload_hash = EXCLUDED.source_payload_hash,
  updated_at = CURRENT_TIMESTAMP;

DROP TABLE IF EXISTS tank_atg_readings;

COMMENT ON TABLE tank_atg_snapshots IS
  'Latest normalized DOMS ATG/TgData snapshot per configured tank. Long-term ATG history is retained in the cloud, not locally.';
