import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const read = (path) => fs.readFileSync(path, 'utf8')

test('station workflow ordering is persisted with backward-compatible defaults', () => {
  const migration = read('scripts/migrations/postgres/1290_station_workflow_ordering.sql')
  const validation = read('src/shared/validations/index.ts')
  const settings = read('src/shared/settings/station.ts')
  const admin = read('src/modules/admin-config/application/saveAdminSettings.ts')
  const form = read('app/(dashboard)/admin/settings/WorkflowOrderingForm.tsx')
  const page = read('app/(dashboard)/admin/settings/client.tsx')

  assert.match(migration, /DEFAULT 'after_fiscalization'/)
  assert.match(migration, /DEFAULT 'after_transaction'/)
  assert.match(migration, /CREATE TABLE IF NOT EXISTS pre_fuel_customer_allocations/)
  assert.match(validation, /printReceiptOrder: z\s*\.enum\(\['before_fiscalization', 'after_fiscalization'\]\)/)
  assert.match(validation, /tinCaptureOrder: z\s*\.enum\(\['before_transaction', 'after_transaction'\]\)/)
  assert.match(settings, /print_receipt_order = COALESCE/)
  assert.match(settings, /tin_capture_order = COALESCE/)
  assert.match(admin, /printReceiptOrder: args\.body\.printReceiptOrder/)
  assert.match(admin, /tinCaptureOrder: args\.body\.tinCaptureOrder/)
  assert.match(form, /name="printReceiptOrder"/)
  assert.match(form, /name="tinCaptureOrder"/)
  assert.match(form, /name="linkingWindowSeconds"/)
  assert.match(form, /name="autoPrintReceipts"/)
  assert.match(form, /tinOrder === 'before_transaction'/)
  assert.match(page, /Transaction workflow/)
  assert.doesNotMatch(page, /<CardTitle>Linking window<\/CardTitle>/)
  assert.doesNotMatch(page, /<CardTitle>Receipt printing<\/CardTitle>/)
  assert.doesNotMatch(page, /LinkingWindowForm/)
  assert.doesNotMatch(page, /AutoPrintReceiptsForm/)
})

test('before-fiscalization receipt printing uses offline print and blocks fiscalization until DONE', () => {
  const autoPrint = read('src/modules/transactions/infrastructure/fiscalization/autoPrintFiscalReceipt.ts')
  const worker = read('src/modules/transactions/infrastructure/fiscalization/offlineReceiptPrintWorker.ts')
  const queue = read('src/modules/transactions/infrastructure/persistence/transaction-queue.repository.ts')
  const sendNow = read('src/modules/transactions/application/commands/send-transaction-to-proxy-now.ts')

  assert.match(autoPrint, /'before_fiscalization'/)
  assert.match(autoPrint, /phase === 'before_fiscalization' \? true/)
  assert.match(autoPrint, /getOrCreatePreFiscalizationReceipt/)
  assert.match(worker, /ss\.print_receipt_order = 'before_fiscalization'/)
  assert.match(worker, /phase: 'before_fiscalization'/)
  assert.match(queue, /preprint\.status = 'DONE'/)
  assert.match(queue, /preprint\.payload->>'offlinePrint'/)
  assert.match(sendNow, /requiresPreFiscalizationReceiptPrint/)
  assert.match(sendNow, /job\?\.status !== 'DONE'/)
})

test('Tanzania pre-fiscal receipt reserves verification prefix plus global counter', () => {
  const assignment = read('src/modules/tanzania-fiscal/infrastructure/preFiscalizationReceiptAssignment.ts')
  const receipt = read('src/modules/transactions/infrastructure/fiscalization/preFiscalizationReceipt.ts')

  assert.match(assignment, /resolveTanzaniaReceiptVerificationPrefix/)
  assert.match(assignment, /'receipt:global'/)
  assert.match(assignment, /const receiptVerificationNumber = `\$\{receiptVerificationPrefix\}\$\{globalCounter\}`/)
  assert.match(assignment, /tanzania_proxy_invoice_assignments/)
  assert.match(receipt, /verificationCode: assignment\.receipt_verification_number/)
  assert.match(receipt, /globalCount: String\(assignment\.global_counter\)/)
  assert.match(receipt, /buildTanzaniaReceiptVerificationUrl/)
  assert.match(receipt, /buildTanzaniaReceiptLines/)
})

test('linking window controls pre-transaction allocation lifetime and after-transaction fiscalization delay', () => {
  const repo = read('src/modules/transactions/infrastructure/preFuelCustomerAllocation.ts')
  const queue = read('src/modules/transactions/infrastructure/persistence/transaction-queue.repository.ts')
  const transactionSql = read('src/modules/transactions/infrastructure/persistence/transaction.sql.ts')

  assert.match(repo, /ss\.linking_window_seconds/)
  assert.match(repo, /COALESCE\(ss\.linking_window_seconds, 0\) <= 0/)
  assert.match(repo, /status = 'CANCELLED'/)
  assert.doesNotMatch(repo, /INTERVAL '4 hours'/)
  assert.match(queue, /ss\.linking_window_seconds/)
  assert.match(queue, /a\.created_at \+ \(ss\.linking_window_seconds \* INTERVAL '1 second'\)/)
  assert.doesNotMatch(queue, /INTERVAL '4 hours'/)
  assert.match(transactionSql, /linking_window_expires_at/)
  assert.match(transactionSql, /created_at \+ \(\$3::int \* INTERVAL '1 second'\)/)
})

test('before-transaction TIN capture is nozzle-specific, durable and single use', () => {
  const api = read('app/api/transactions/pre-fuel-customer/route.ts')
  const command = read('src/modules/transactions/application/commands/manage-pre-fuel-customer.ts')
  const authorize = read('src/modules/transactions/application/commands/authorize-pre-fuel-customer.ts')
  const repo = read('src/modules/transactions/infrastructure/preFuelCustomerAllocation.ts')
  const queue = read('src/modules/transactions/infrastructure/persistence/transaction-queue.repository.ts')

  assert.match(api, /roles: \['tenant', 'manager', 'administrator'\]/)
  assert.match(api, /body\.action === 'authorize'/)
  assert.match(api, /allocatePreFuelCustomer/)
  assert.match(command, /cancelPreFuelCustomerAllocation/)
  assert.doesNotMatch(command, /command: 'preFuelCustomer'/)
  assert.match(authorize, /getPumpRuntimeState/)
  assert.match(authorize, /nozzleState === 'calling'/)
  assert.match(authorize, /nozzleState === 'nozzle_up'/)
  assert.match(authorize, /command: 'preFuelCustomer'/)
  assert.match(repo, /ON CONFLICT \(station_id, pump_number, nozzle_number\)/)
  assert.match(repo, /status = 'CONSUMED'/)
  assert.match(queue, /ss\.tin_capture_order = 'before_transaction'/)
  assert.match(queue, /customer_id = candidates\.customer_id/)
  assert.match(queue, /'infinity'::timestamptz/)
})

test('before-transaction TIN allocation is available to operational roles with a DOMS pump board', () => {
  const migration = read('scripts/migrations/postgres/1300_nozzle_display_number.sql')
  const sidebar = read('components/layout/sidebar.tsx')
  const layout = read('app/(dashboard)/layout.tsx')
  const page = read('app/(dashboard)/tin-allocation/page.tsx')
  const board = read('components/transactions/TinAllocationClient.tsx')
  const fuelOptions = read('src/modules/transactions/application/queries/list-fuel-options.ts')
  const pumpState = read('app/api/pumps/state/route.ts')
  const pumpNozzles = read('src/modules/settings/application/pumpNozzles.ts')
  const settingsClient = read('app/(dashboard)/settings/pumps/[id]/client.tsx')

  assert.match(migration, /ADD COLUMN IF NOT EXISTS display_number INTEGER/)
  assert.match(migration, /SET display_number = nozzle_number/)
  assert.match(migration, /uq_nozzles_active_display_number/)
  assert.match(sidebar, /label: 'TIN Allocation'/)
  assert.match(sidebar, /tinCaptureOrder === 'before_transaction'/)
  assert.doesNotMatch(sidebar, /role === 'tenant' && tinCaptureOrder/)
  assert.match(layout, /tinCaptureOrder=\{tinCaptureOrder\}/)
  assert.match(page, /requireAuth\(\['tenant', 'manager', 'administrator'\]\)/)
  assert.match(page, /settings\?\.tin_capture_order !== 'before_transaction'/)
  assert.match(page, /TinAllocationClient/)
  assert.match(board, /fetch\('\/api\/pumps\/state'/)
  assert.match(board, /previousHasLive && !nextHasLive \? previous : next/)
  assert.match(board, /Pump \{pumpNumber\}/)
  assert.match(board, /Nozzle/)
  assert.match(board, /option\.displayNumber \?\? option\.nozzleNumber/)
  assert.match(board, /formatState\(state\)/)
  assert.match(board, /Allocate customer/)
  assert.match(board, /Authorize nozzle/)
  assert.match(board, /Waiting for DOMS CALLING state/)
  assert.match(fuelOptions, /COALESCE\(n\.display_number, n\.nozzle_number\)/)
  assert.match(pumpState, /roles: \['tenant', 'administrator', 'manager'\]/)
  assert.match(pumpNozzles, /displayNumber/)
  assert.match(settingsClient, /Display number/)
  assert.match(settingsClient, /Controller nozzle \/ grade number/)
})
