export type PosDomsRouteCommand =
  | 'changeDynamicTankData'
  | 'changeGradePrices'
  | 'getAllTankDeliveryData'
  | 'getAllTgData'
  | 'getSiteDeliveryStatus'
  | 'getTgStatus'
  | 'clearTankDeliveryData'
  | 'openTankController'
  | 'closeTankController'
  | 'startDeliveryProcess'
  | 'stopDeliveryProcess'
  | 'getGradePrices'
  | 'getTgErrorMsg'
