export type PosCommandType =
  | 'POS_STATUS'
  | 'COMPLETE_TRANSACTION'
  | 'CAPTURE_CUSTOMER_DETAILS'
  | 'CLEAR_CUSTOMER_DETAILS'
  | 'GET_DAILY_DATA'
  | 'PING'
  | 'OPEN_FPS'
  | 'CLOSE_FPS'
  | 'ATTENDANT_AUTH'
  | 'PREFUEL_CUSTOMER'
  | 'CLEAR_PREFUEL_CUSTOMER'
  | 'CLEAR_FP_ERROR'
  | 'GET_GRADE_PRICES'
  | 'CHANGE_GRADE_PRICES'
  | 'CLEAR_PENDING_PRICE_SET'
  | 'GET_ALL_TANK_DELIVERY_DATA'
  | 'GET_ALL_TG_DATA'
  | 'CHANGE_DYNAMIC_TANK_DATA'
  | 'GET_TG_ERROR_MSG'
  | 'GET_FP_GRADE_TOTALS'
  | 'GET_PUMP_GRADE_TOTALS'
  | 'GET_PUMP_GRADE_BLEND_TOTALS'
  | 'GET_FALLBACK_TOTALS'
  | 'CLEAR_FALLBACK_TOTALS'
  | 'GET_TANK_CONTROL_STATUS'
  | 'MARK_DELIVERY_STARTING'
  | 'MARK_DELIVERY_FINISHED'
  | 'BLOCK_TANK'
  | 'UNBLOCK_TANK'
  | 'CLEAR_TG_ERROR'
  | 'RESET_TG'
  | 'GET_FC_DATE_TIME'
  | 'CHANGE_FC_DATE_TIME'
  | 'GET_FC_OPERATION_MODE_STATUS'
  | 'CHANGE_FC_OPERATION_MODE'
  | 'UTIL_ECHO'

export const POS_COMMAND_TYPES: PosCommandType[] = [
  'POS_STATUS',
  'COMPLETE_TRANSACTION',
  'CAPTURE_CUSTOMER_DETAILS',
  'CLEAR_CUSTOMER_DETAILS',
  'GET_DAILY_DATA',
  'PING',
  'OPEN_FPS',
  'CLOSE_FPS',
  'ATTENDANT_AUTH',
  'PREFUEL_CUSTOMER',
  'CLEAR_PREFUEL_CUSTOMER',
  'CLEAR_FP_ERROR',
  'GET_GRADE_PRICES',
  'CHANGE_GRADE_PRICES',
  'CLEAR_PENDING_PRICE_SET',
  'GET_ALL_TANK_DELIVERY_DATA',
  'GET_ALL_TG_DATA',
  'CHANGE_DYNAMIC_TANK_DATA',
  'GET_TG_ERROR_MSG',
  'GET_FP_GRADE_TOTALS',
  'GET_PUMP_GRADE_TOTALS',
  'GET_PUMP_GRADE_BLEND_TOTALS',
  'GET_FALLBACK_TOTALS',
  'CLEAR_FALLBACK_TOTALS',
  'GET_TANK_CONTROL_STATUS',
  'MARK_DELIVERY_STARTING',
  'MARK_DELIVERY_FINISHED',
  'BLOCK_TANK',
  'UNBLOCK_TANK',
  'CLEAR_TG_ERROR',
  'RESET_TG',
  'GET_FC_DATE_TIME',
  'CHANGE_FC_DATE_TIME',
  'GET_FC_OPERATION_MODE_STATUS',
  'CHANGE_FC_OPERATION_MODE',
  'UTIL_ECHO',
]

export type PosCommandRequest = {
  type: PosCommandType
  payload?: any
}

export type PosCommandResult = {
  ok: boolean
  type: PosCommandType
  data?: any
  error?: { message: string; code?: string; details?: any }
}
